To Correct:
  - changed-files:
In Progress:
  - changed-files:
To Deploy on STG:
  - changed-files:
CR:
  - changed-files:
Master:
  - changed-files:
Staging:
  - changed-files:
      - any-glob-to-any-file: '*'
      - any-glob-to-any-file: '**'