name: Label Assign Action

inputs:
  workflow-status:
    description: The result of previous step execution
    required: true
  drafted:
    description: Information about is drafted PR
    required: true

runs:
  using: composite
  steps:
    - name: Determine label configuration path
      id: determine-label
      shell: bash
      run: |
        if [[ "${{ inputs.drafted }}" == "true" ]]; then
          echo "label_config=.github/labels-groups/progress.yml" >> $GITHUB_ENV
        elif [[ "${{ inputs.workflow-status }}" == "success" ]]; then
          echo "label_config=.github/labels-groups/success.yml" >> $GITHUB_ENV
        elif [[ "${{ inputs.workflow-status }}" == "failure" ]]; then
          echo "label_config=.github/labels-groups/failure.yml" >> $GITHUB_ENV
        else
          echo "No applicable label configuration found."
          exit 1
    - name: Assign appropriate label
      if: ${{ env.label_config }}
      uses: actions/labeler@v5
      with:
        configuration-path: ${{ env.label_config }}
        sync-labels: true