name: Label Assign Action

inputs:
  workflow-status:
    description: The result of previous step execution
    required: true
  drafted:
    description: Information about is drafted PR
    required: true
  event_name:
    description: Information about type of event
    required: true

runs:
  using: composite
  steps:
    - name: Assign progress label
      if: ${{ inputs.drafted == 'true' && inputs.event_name == 'pull_request' }}
      uses: actions/labeler@v5
      with:
        configuration-path: '.github/labels-groups/progress.yml'
        sync-labels: true
    - name: Assign success label
      if: ${{ inputs.drafted == 'false' && inputs.workflow-status == 'success' && inputs.event_name == 'pull_request' }}
      uses: actions/labeler@v5
      with:
        configuration-path: '.github/labels-groups/success.yml'
        sync-labels: true
    - name: Assign failure label
      if: ${{ inputs.drafted == 'false' && inputs.workflow-status == 'failure' && inputs.event_name == 'pull_request' }}
      uses: actions/labeler@v5
      with:
        configuration-path: '.github/labels-groups/failure.yml'
        sync-labels: true
    - name: Assign Ready to Stage label
      if: ${{ inputs.drafted == 'false' && inputs.event_name == 'pull_request_review' }}
      uses: actions/labeler@v5
      with:
        configuration-path: '.github/labels-groups/ready-to-stage.yml'
        sync-labels: true
