name: Label Assign Action

inputs:
  workflow-status:
    description: The result of previous step execution
    required: true
  drafted:
    description: Information about is drafted PR
    required: true

runs:
  using: composite
  steps:
    - name: Assign progress label
      if: ${{ inputs.drafted }}
      uses: actions/labeler@v5
      with:
        configuration-path: '.github/labels-groups/progress.yml'
        sync-labels: true
    - name: Assign success label
      if: ${{ !inputs.drafted && inputs.workflow-status == 'success' }}
      uses: actions/labeler@v5
      with:
        configuration-path: '.github/labels-groups/success.yml'
        sync-labels: true
    - name: Assign failure label
      if: ${{ !inputs.drafted && inputs.workflow-status == 'failure' }}
      uses: actions/labeler@v5
      with:
        configuration-path: '.github/labels-groups/failure.yml'
        sync-labels: true
