name: Build and Test

on:
  push:
    branches: [main, staging]
  pull_request:
    types:
      - opened
      - ready_for_review

concurrency:
  group: ${{github.workflow}}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  build-test:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      pull-requests: write
    steps:
      - name: Sleep for 360 seconds
        run: sleep 360
      - uses: actions/checkout@v4
      - name: Build Application
        uses: ./.github/actions/build
        with:
          node-version: '20.11.0'
      - name: Run Tests
        uses: ./.github/actions/test