name: Development CI

on:
  pull_request:
    types:
      - opened
      - synchronize
      - reopened
      - ready_for_review
      - converted_to_draft
  pull_request_review:
    types:
      - submitted

jobs:
  build-test:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      pull-requests: write
    steps:
      - uses: actions/checkout@v4
      - name: Build Application
        if: github.event_name == 'pull_request'
        uses: ./.github/actions/build
        with:
          node-version: '20.11.0'
      - name: Run Tests
        if: github.event_name == 'pull_request'
        uses: ./.github/actions/test
      - name: Assign Labels
        if: always()
        uses: ./.github/actions/labels
        with:
          workflow-status: ${{ job.status }}
          drafted: ${{ github.event.pull_request.draft }}
          event_name: ${{ github.event_name }}