name: GitHub Actions Labeler
run-name: ${{ github.event.workflow_run.workflow_id }} ${{ github.job }}
on:
  pull_request:
jobs:
  labeler:
    permissions:
      contents: read
      pull-requests: write
    runs-on: ubuntu-latest
    steps:
      - uses: actions/labeler@v5
