name: Run Lighthouse CRON CI

on:
  push:

concurrency:
  group: ${{github.workflow}}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  lhci:
    name: Audit with Lighthouse CI
    runs-on: ubuntu-latest

    strategy:
      fail-fast: false
      matrix:
        url:
          - https://www.gazetkowo.pl
        form_factor: [desktop, mobile]

    steps:
      - uses: actions/checkout@v4

      - name: Audit URLs using Lighthouse
        uses: treosh/lighthouse-ci-action@v12
        env:
          LHCI_FORM_FACTOR: ${{ matrix.form_factor }}
        with:
          urls: ${{ matrix.url }}
          runs: 1
          budgetPath: ./.lighthouse/budget.json
          configPath: ./.lighthouse/lighthouserc.cjs
          uploadArtifacts: true
          temporaryPublicStorage: false
          artifactName: lighthouse-${{ matrix.form_factor }}-${{ github.run_id }}-${{ github.run_attempt }}
        continue-on-error: false