name: Run Lighthouse CRON CI

on:
  push:
    branches:
      - 'lighthouse_v2'

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  lhci:
    name: Audit with Lighthouse CI (${{ matrix.preset }})
    runs-on: ubuntu-latest

    strategy:
      fail-fast: false
      matrix:
        preset: [desktop, mobile]

    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Setup Node (>= 18.20)
        uses: actions/setup-node@v4
        with:
          node-version: '18.20.x'

      - name: Install Chrome
        id: setup-chrome
        uses: browser-actions/setup-chrome@v1

      - name: Install Lighthouse CI CLI
        run: npm i -g @lhci/cli

      - name: Run Lighthouse CI (collect + assert + upload)
        env:
          CHROME_PATH: ${{ steps.setup-chrome.outputs.chrome-path }}
        run: |
          echo "Chrome path: ${CHROME_PATH:-$(which google-chrome || true)}"
          # Override preset and output directory per matrix entry.
          lhci autorun \
            --config=lighthouserc.json \
            --collect.settings.preset=${{ matrix.preset }} \
            --upload.outputDir=lhci-reports-${{ matrix.preset }}

      - name: Upload ${{ matrix.preset }} reports
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: lighthouse-reports-${{ matrix.preset }}
          path: lhci-reports-${{ matrix.preset }}/**