name: Run Lighthouse CRON CI

on:
    push:

jobs:
    lhci:
        name: Audit with Lighthouse CI
        runs-on: ubuntu-latest

        strategy:
            fail-fast: false
            matrix:
                url:
                    - https://www.gazetkowo.pl
                form_factor: [desktop, mobile]

        steps:
            - uses: actions/checkout@v4

            - name: Audit URLs using Lighthouse
              id: lhci
              uses: treosh/lighthouse-ci-action@v12
              env:
                  LHCI_FORM_FACTOR: ${{ matrix.form_factor }}
              with:
                urls: ${{ matrix.url }}
                runs: 1
                budgetPath: ./.lighthouse/budget.json
                configPath: ./.lighthouse/lighthouserc.cjs
                uploadArtifacts: true
                temporaryPublicStorage: false