name: Run Lighthouse CRON CI

on:
  push:
    branches:
      - 'lighthouse_v2'

concurrency:
  group: ${{github.workflow}}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  lhci:
    name: Audit with Lighthouse CI
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Setup Node (>= 18.20)
        uses: actions/setup-node@v4
        with:
          node-version: '18.20.x'

      - name: Install Chrome
        uses: browser-actions/setup-chrome@v1

      - name: Install Lighthouse CI CLI
        run: npm i -g @lhci/cli

      # If the config file is committed, you can drop this step.
      - name: Write lighthouserc.json
        run: |
          cat > lighthouserc.json <<'JSON'
          {
            "ci": {
              "collect": {
                "url": ["https://www.gazetkowo.pl"],
                "numberOfRuns": 1,
                "startServerCommand": "",
                "settings": {
                  "preset": "desktop",
                  "chromeFlags": "--headless --no-sandbox"
                }
              },
              "assert": {
                "assertions": {
                  'lighthouse-run-warnings': 'error',
                  'runtime-error': 'error',
          
                  "categories:performance": ["error", {"minScore": 0.80}],
                  "categories:accessibility": ["warn", {"minScore": 0.90}],
                  "categories:seo": ["warn", {"minScore": 0.90}],
                  "categories:best-practices": ["warn", {"minScore": 0.90}]
          
                  'first-contentful-paint':   ['error', { maxNumericValue: 2500, aggregationMethod: 'median' }],
                  'largest-contentful-paint': ['error', { maxNumericValue: 4000, aggregationMethod: 'median' }],
                  'total-blocking-time':      ['error', { maxNumericValue: 300,  aggregationMethod: 'median' }],
                  'cumulative-layout-shift':  ['error', { maxNumericValue: 0.10, aggregationMethod: 'median' }],
                  'speed-index':              ['error', { maxNumericValue: 4300, aggregationMethod: 'median' }],
                }
              },
              "upload": {
                "target": "filesystem",
                "outputDir": "lhci-reports"
              }
            }
          }
          JSON

      - name: Run Lighthouse CI (collect + assert + upload)
        env:
          CHROME_PATH: ${{ steps.setup-chrome.outputs.chrome-path }}
        run: |
          echo "Chrome path: ${CHROME_PATH:-$(which google-chrome || true)}"
          lhci autorun --config=lighthouserc.json

      - name: Upload reports
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: lighthouse-reports
          path: |
            lhci-reports/**
            .lighthouseci/**