name: GitHub Actions Demo
run-name: ${{ github.action_status }} ${{ github.path }} ${{ github.job }} ${{ github.run_attempt }}
on: [push]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 20.11.0
          cache: 'npm'
      - name: Install dependencies
        run: npm install
      - name: Build Application
        run: npm run build
  test:
    needs: build
    runs-on: ubuntu-latest
    steps:
    - name: Checkout code
      uses: actions/checkout@v3
    - name: Set up Node.js
      uses: actions/setup-node@v4
      with:
        node-version: 20.11.0
        cache: 'npm'
    - name: Install dependencies
      run: npm install
    - name: Run Tests
      run: npm run test
