name: Staging CI

on:
  push:
    branches:
      - staging

jobs:
  tests:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Log push on staging
        run: echo "Hello staging"


